#!/usr/bin/env python

print "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
print "!!! You are using an old startup method for OctoPrint. !!!"
print "!!! Please perform 'sudo python setup.py install' and  !!!"
print "!!! use 'octoprint' instead                            !!!"
print "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
print

import sys
sys.path.append("src")

from octoprint import main
main()
